#!/bin/sh
psql -U postgres << EOF

CREATE ROLE nakrole
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE nakamura LOGIN
  ENCRYPTED PASSWORD 'md5485b09f5c7782720e1a525aae3c96b36'
  NOSUPERUSER INHERIT CREATEDB NOCREATEROLE;
GRANT nakrole TO nakamura;

CREATE DATABASE nak
  WITH OWNER = nakamura
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

EOF
